#!/usr/bin/env python3
"""Base64-embeds every PNG in assets/ into src/assets_data.js so the game
can be opened directly by double-clicking index.html (file:// blocks the
XHR/fetch requests Phaser's loader normally uses to fetch image files,
so we hand it data URIs instead, which need no network request at all)."""

import base64
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
ASSETS_DIR = os.path.join(ROOT, "assets")
OUT_FILE = os.path.join(ROOT, "src", "assets_data.js")

KEY_BY_FILE = {
    "bg_sky.png": "sky",
    "bg_trees_far.png": "trees_far",
    "bg_trees_near.png": "trees_near",
    "ground.png": "ground",
    "fence.png": "fence",
    "lantern.png": "lantern",
    "gate.png": "gate",
    "hero.png": "hero",
    "goblin.png": "goblin",
    "wolf.png": "wolf",
    "slime.png": "slime",
}

def main():
    entries = []
    for filename, key in KEY_BY_FILE.items():
        path = os.path.join(ASSETS_DIR, filename)
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        entries.append(f'  {key}: "data:image/png;base64,{b64}",')
        print("embedded", filename, "->", key, f"({len(b64)} b64 chars)")

    with open(OUT_FILE, "w") as f:
        f.write("// Auto-generated by tools/embed_assets.py - do not edit by hand.\n")
        f.write("const ASSET_DATA = {\n")
        f.write("\n".join(entries))
        f.write("\n};\n")
    print("wrote", OUT_FILE)

if __name__ == "__main__":
    main()
