#!/usr/bin/env python3
"""Base64-embeds every PNG in assets/ into src/assets_data.js so the game
can be opened directly by double-clicking index.html (file:// blocks the
XHR/fetch requests Phaser's loader normally uses to fetch image files,
so we hand it data URIs instead, which need no network request at all)."""

import base64
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
ASSETS_DIR = os.path.join(ROOT, "assets")
OUT_FILE = os.path.join(ROOT, "src", "assets_data.js")

def main():
    entries = []
    total = 0
    for filename in sorted(os.listdir(ASSETS_DIR)):
        if not filename.endswith(".png"):
            continue
        key = filename[:-4]  # the game looks assets up by bare filename
        path = os.path.join(ASSETS_DIR, filename)
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        entries.append(f'  {key}: "data:image/png;base64,{b64}",')
        total += len(b64)
        print(f"embedded {filename:24s} -> {key:18s} ({len(b64):7d} b64 chars)")
    print(f"total base64: {total / 1024:.0f} KiB")

    with open(OUT_FILE, "w") as f:
        f.write("// Auto-generated by tools/embed_assets.py - do not edit by hand.\n")
        f.write("const ASSET_DATA = {\n")
        f.write("\n".join(entries))
        f.write("\n};\n")
    print("wrote", OUT_FILE)

if __name__ == "__main__":
    main()
